# =================================================================================================
# CREATING VISUALIZATIONS FOR OKLAHOMA

# Author: Michael Jetsupphasuk
# Last Updated: 11 December, 2017

# This file creates plots for data exploration. Read the .csv files generated by clean.R or load
# the relevant .RData.


# =================================================================================================

# LOAD LIBRARIES ----------------------------------------------------------

library(dplyr)
library(stringr)
library(tidyr)

library(maps)
library(maptools)

library(sp)  # vector data
library(raster)  # raster data
library(rgdal)  # input/output, projections
library(rgeos)  # geometry ops
library(spdep)  # spatial dependence

library(ggmap)
# citation('ggmap')

library(spatstat)


# READ DATA ---------------------------------------------------------------

# load california data
load("ok_data.RData")

water = read.csv("data/final_water_ok.csv")
eqs = read.csv("data/final_eqs_ok.csv")
blocks = read.table("data/final_blocks_ok.txt")[ , 1]
months = read.table("data/months.txt")[ , 1]
months = months[373:444] # only keep relevant months


# GLOBAL PARAMETERS -------------------------------------------------------

# convert a time series (numeric vector) to cummulative ts (not on 0-1 scale)
convert_cumm <- function(vec){
  first_vec = vec[1]
  if (length(vec) == 1){
    return(first_vec)
  }
  vec[2] = vec[1] + vec[2]
  return(c(first_vec, convert_cumm(vec[2:length(vec)])))
}


# SIMPLE EXPLORATORY -------------------------------------------------------------

# time series of wells in aggregate

all_inj = colSums(water)
plot(all_inj, type = 'b', xaxt = 'n')
axis(side=1, at=1:length(all_inj), labels=months)


# wells, earthquakes, grid on california map

okl_spolys_df = fortify(okl_spolys)
grid_df = data.frame(SpatialPoints(grid, my_crs)@coords)
ggplot() +
  geom_polygon(data = okl_spolys_df, aes(x = long, y = lat, group = group)) +
  geom_tile(data = grid_df, aes(x = x1, y = x2), color = 'yellow', alpha = 0) +
  geom_point(data = ok_eq, aes(x = longitude, y = latitude, color = time_year), show.legend = F, size = .75) +
  geom_point(data = wells_wide, aes(x = Long_X, y = Lat_Y), show.legend = F, size = .75, color = 'red')



# INJECTIONS + EARTHQUAKES EACH BLOCK -------------------------------------

# get cummulative water injected per block
cumm_water = rowSums(water)

# get cummulative earthquakes per block
cumm_eq = rowSums(eqs)

# plot earthquakes, water injection time series for each relevant block
for (i in 1:length(blocks)){
  
  # non cummulative plots
  
  # save plots
  path_save = paste0("pictures/eq_inj_ok/not_cumm/", "grid", blocks[i], ".jpeg")
  jpeg(filename = path_save,
       width = 1500, height = 600)
  
  par(mfrow = c(2,1))
  
  plot(as.numeric(water[i, ]), type = 'l', xaxt = 'n', col = 'blue',
       main = "Wastewater Injection Time Series",
       xlab = "Time (months)",
       ylab = "Injections (bbl)")
  axis(side=1, at=1:ncol(water), labels=months)
  
  plot(as.numeric(eqs[i, ]), col = 'red', xaxt = 'n', type = 'l',
       main = "Earthquake Time Series",
       xlab = "Time (months)",
       ylab = "Number of Earthquakes (>2.5)")
  axis(side=1, at=1:ncol(eqs), labels=months)
  
  dev.off()
  
  ###############################################################################  
  
  # cummulative plots (do not normalize to 0-1 scale)
  
  # save plots
  path_save = paste0("pictures/eq_inj_ok/cumm/", "grid", blocks[i], ".jpeg")
  jpeg(filename = path_save,
       width = 1500, height = 600)
  
  par(mfrow = c(2,1))
  
  plot(convert_cumm(as.numeric(water[i, ])), type = 'l', xaxt = 'n', col = 'blue',
       main = "Cumm. Wastewater Injection Time Series",
       xlab = "Time (months)",
       ylab = "Cumm. Injections (bbl)")
  axis(side=1, at=1:ncol(water), labels=months)
  
  plot(convert_cumm(as.numeric(eqs[i, ])), col = 'red', xaxt = 'n', type = 'l',
       main = "Cumm. Earthquake Time Series",
       xlab = "Time (months)",
       ylab = "Number of Earthquakes (>2.5)")
  axis(side=1, at=1:ncol(eqs), labels=months)
  
  dev.off()
}


