# =================================================================================================
# GET EARTHQUAKE DATA

# Author: Michael Jetsupphasuk
# Last Updated: 31 October, 2017

# Pull Date: 31 October, 2017

# This file uses code and data provided by the United States Geological Survey (USGS).
# Code from github: https://github.com/usgs/devcorner
# Gets earthquake data with the following parameters
#     - Minimum Magnitude: 3.0
#     - Start Time: 1980-01-01 00:00:00
#     - End Time: 2017-10-01 23:59:59
#     - Minimum Latitude: 32.495
#     - Maximum Latitude: 42.183
#     - Minimum Longitude: -124.805
#     - Maximum Longitude: -113.994
# Write data as .csv

# Note: data generated by this file is not exclusively california - queries long/lat box

# =================================================================================================

# Use query function provided by USGS
source('rcomcat/searchcomcat.R')

# Set start and end times
stime = as.POSIXct("1980-01-01 00:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
etime = as.POSIXct("2017-10-16 23:59:59", format = "%Y-%m-%d %H:%M:%S", tz = "UTC")

# Get data
eq_dat = comcathypocsv(minmagnitude = 3,
                    starttime = stime,
                    endtime = etime,
                    minlatitude = 32.495,
                    maxlatitude = 42.183,
                    minlongitude = -124.805,
                    maxlongitude = -113.994,
                    eventtype = "earthquake")

# Write data
write.csv(eq_dat, "rawdata/earthquakes/california/ca_eq_raw.csv")
