# =================================================================================================
# GET OKLAHOMA EARTHQUAKE DATA

# Author: Michael Jetsupphasuk
# Last Updated: 11 December, 2017

# Pull Date: 11 December, 2017

# This file uses code and data provided by the United States Geological Survey (USGS).
# Code from github: https://github.com/usgs/devcorner
# Gets earthquake data with the following parameters
#     - Minimum Magnitude: 3.0
#     - Start Time: 2011-01-01 00:00:00
#     - End Time: 2016-12-31 23:59:59
#     - Minimum Latitude: 33.210
#     - Maximum Latitude: 37.194
#     - Minimum Longitude: -103.228
#     - Maximum Longitude: -93.867
# Write data as .csv

# Note: data generated by this file is not exclusively oklahoma - queries long/lat box

# =================================================================================================

# Use query function provided by USGS
source('rcomcat/searchcomcat.R')

# Set start and end times
stime = as.POSIXct("2011-01-01 00:00:00", format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
etime = as.POSIXct("2016-12-31 23:59:59", format = "%Y-%m-%d %H:%M:%S", tz = "UTC")

# Get data
eq_dat = comcathypocsv(minmagnitude = 3,
                    starttime = stime,
                    endtime = etime,
                    minlatitude = 33.210,
                    maxlatitude = 37.194,
                    minlongitude = -103.228,
                    maxlongitude = -93.867,
                    eventtype = "earthquake")

# Write data
write.csv(eq_dat, "rawdata/earthquakes/oklahoma/ok_eq_raw.csv", row.names = F)
